default: &default
  DATABASE_HOST: localhost
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'postgres'
  WEB_HOST: 'localhost'
  STU_NUMBER: '201440922217'
  STU_PASSWORD: '834749'

  WECHAT_APPID: 'wxbc23727752384330'
  WECHAT_APPSECRET: '16df3fe144ff739a8eefb0d0471a0842'

  HUNAU_API_PARAMS_AK: 'agsvURNWGfPqrxLKF2ZW7b7f'
  HUNAU_API_PARAMS_BDUSERID: '1087502747626781624%7C5491757748890217134%7C4'
  HUNAU_API_PARAMS_PRIDORMID: 'CPES_LC'
  HUNAU_API_PARAMS_VID: 'aijfdfdlsafdsaff'
  HUNAU_API_PARAMS_NEWS_ID: '098765'
  HUNAU_API_PARAMS_USER_FLAG: '20141114095328475'
  HUNAU_API_PARAMS_GRADE__: '1520691591608' # 请求成绩不知道干什么的参数

development:
  <<: *default
  HOSTNAME: 'http://localhost:3030'

test:
  <<: *default
  HOSTNAME: 'http://localhost:3030'

staging:
  <<: *default
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'hYG59287'
  SECRET_KEY_BASE: 'aa415858c2d1301b8fa0b31c4276e7f5e7b1bb9a16ad4b638d2606ae13eceb430dcdc73eed047a2aa41513e10d18ddbe897269c428ebc730b1b6570a04fc6751'
  WEB_HOST: ''

production:
  <<: *default
  WEB_HOST: ''
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'postgres'
  SECRET_KEY_BASE: 'aa415858c2d1301b8fa0b31c4276e7f5e7b1bb9a16ad4b638d2606ae13eceb430dcdc73eed047a2aa41513e10d18ddbe897269c428ebc730b1b6570a04fc6710'

