hunauapi:
  service_host: 'http://zsxy.hunau.edu.cn/api'
  service_news_host: 'http://zsxy.hunau.edu.cn/mobile'
  service_endpoint: '/NDAppWebService.asmx'
  service_post_endpoint: '/MUIInterface.asmx'
  service_news_endpoint: '/ajax/ArticleInfo_H.ashx'
  service_grades_endpoint: '/ResultsQuery'

  init_pridormid: 'CPES_LC'
  callback: 'loadCJ_JsonpCallback'
  login_path: '/WSMemberLogin'
  get_room_path: '/GETROOM'
  get_news_path: '/Newsget'
  get_energy_query: '/EnergyQuery'
  get_surplus_query: '/QuerySurplus'
  get_term: '/GetTerm'
  get_timetable: '/GetStudentsKb'
  get_tranitem: '/GettranItem'
  get_brows: '/GetBrows'
  get_loss: '/GetReport'
  get_borrow: '/WSGetWjCx'
  get_today_borrows: '/GetTodayBrows'

wechatapi:
  service_host: 'https://api.weixin.qq.com/sns/jscode2session?'
  grant_type: 'authorization_code'

FindBook:
  service_host: 'http://59.41.253.10:7781'
  hot_keys_path: '/Logs/stvisitkey_ifa_GetList.ashx'
  book_search_path: '/Find/find_ifa_FindFullPage.ashx'
  book_detail_path: '/Find/find_ifa_GetDetail.ashx'
  book_lib_coll_path: '/Find/find_ifa_GetOpacColl2.aspx'
  book_lib_site_path: '/Find/find_ifa_GetSiteColl.aspx'

