hunauapi:
  service_host: 'http://zsxy.hunau.edu.cn/api'
  service_endpoint: '/NDAppWebService.asmx'
  service_post_endpoint: '/MUIInterface.asmx'

  init_pridormid: 'CPES_LC'
  login_path: '/WSMemberLogin'
  get_room_path: '/GETROOM'

wechatapi:
  service_host: 'https://api.weixin.qq.com/sns/jscode2session?'
  grant_type: 'authorization_code'

