hunauapi:
  service_host: 'http://zsxy.hunau.edu.cn/api'
  service_news_host: 'http://zsxy.hunau.edu.cn/mobile'
  service_endpoint: '/NDAppWebService.asmx'
  service_post_endpoint: '/MUIInterface.asmx'
  service_news_endpoint: '/ajax/ArticleInfo_H.ashx'
  service_grades_endpoint: '/ResultsQuery'

  init_pridormid: 'CPES_LC'
  callback: 'loadCJ_JsonpCallback'
  login_path: '/WSMemberLogin'
  get_room_path: '/GETROOM'
  get_news_path: '/Newsget'
  get_energy_query: '/EnergyQuery'
  get_surplus_query: '/QuerySurplus'
  get_term: '/GetTerm'
  get_timetable: '/GetStudentsKb'

wechatapi:
  service_host: 'https://api.weixin.qq.com/sns/jscode2session?'
  grant_type: 'authorization_code'

